version: '3.8'

services:
  postgres:
    image: 'postgres'
    restart: always
    env_file: ./.env
    environment:
      - POSTGRES_USER= ${POSTGRES_USER}
      - POSTGRES_PASSWORD= ${POSTGRES_PASSWORD}
      - POSTGRES_DB= ${POSTGRES_DB}
    volumes:
      - postgres-volume-test:/var/lib/postgresql/data
      # run sql start-up scripts to create and populate tables:
      - ./db/createDbTables.sql:/docker-entrypoint-initdb.d/createDbTables.sql
      - ./db/populateDbTables.sql:/docker-entrypoint-initdb.d/populateDbTables.sql

  ministrynameapp:
    image: ministrynameapp
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    env_file: ./.env
    stdin_open: true
    tty: true
    ports:
      - '3000:3000'

volumes:
  postgres-volume-test:
    name: postgres-volume-test

